---
- name: Create New User
  hosts: 40.40.40.50
  become: true
  gather_facts: false
  vars:
# Define your username and password here that you want to create on target hosts.
    username: admin
    userpass: user_password
  tasks:
    - name: Create User
      ansible.builtin.user:
        name: "{{ username }}"
        state: present
        shell: /bin/bash
        password: "{{ userpass | password_hash('sha512') }}"
        update_password: on_create
        #groups: "{{ super_group }}"
        append: yes

    - name: Deploy SSH Public Key
      ansible.posix.authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', '/home/ubuntu/.ssh/id_rsa.pub') }}"

    - name: Add "{{ username }}" user to the sudoers
      copy:
            dest: "/etc/sudoers.d/{{ username }}"
            content: "{{ username }}  ALL=(ALL)  NOPASSWD: ALL"
# Enable PubkeyAuthentication
   - name: Enable key Authentication
     lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PubkeyAuthentication'
           line="PubkeyAuthentication yes"
           state=present
           backup=yes
     notify:
       - restart ssh
 
   handlers:
   - name: restart ssh
     service:
       name=sshd
       state=restarted