---
- hosts: all
  become: yes
  become_user: root
  tasks:

    - name: install linux-tools-common
      apt:
         name: linux-tools-common
         update_cache: true

    - name: install net-tools
      apt:
         name: net-tools
         update_cache: true
      


