---
- hosts: k8s
  become: true
  become_user: root
  tasks:

    - name: install open-iscsi
      apt:
        name: open-iscsi
        state: latest
        update_cache: yes

    - name: install NFS-common
      apt:
        name: nfs-common
        state: latest
